eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 9090

spring:
  application:
    name: GIFT-SERVICE
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: giftdb
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

security:
  oauth2:
    client:
      client-id: client
      client--secret: secret
    resource:
      token-info-uri: http://localhost:9093/oauth/check_token
